import { PrismaClient } from '@prisma/client'
const p = new PrismaClient()

const lessons = await p.lesson.findMany({where:{slug:{in:['c8-l1','c8-l2','c8-l3','c8-l4','c8-l5']}}})
for(const l of lessons) {
  const exos = await p.exercise.findMany({where:{lessonId:l.id}})
  for(const e of exos) await p.answerOption.deleteMany({where:{exerciseId:e.id}})
  await p.exercise.deleteMany({where:{lessonId:l.id}})
}
const bySlug = Object.fromEntries(lessons.map(l => [l.slug, l.id]))

const data = {
  'c8-l1': [
    { q: "Pour créer un assistant personnel IA efficace, quelle est la première étape ?", exp: "Définir précisément le rôle et le contexte de l'assistant est crucial. Un assistant vague donne des réponses vagues. Plus tu définis sa personnalité, ses limites et son domaine, plus il sera utile.", opts: [["Choisir le meilleur LLM disponible", false],["Définir précisément le rôle, le contexte et les limites de l'assistant", true],["Créer un compte premium", false],["Apprendre à programmer", false]] },
    { q: "Qu'est-ce qu'un 'system prompt' dans un assistant IA ?", exp: "Le system prompt est l'instruction initiale cachée qui définit le comportement de l'assistant. C'est là qu'on précise son rôle, son ton, ses limites et son contexte. Il s'applique à toute la conversation.", opts: [["Le premier message de l'utilisateur", false],["L'instruction initiale qui définit le comportement de l'assistant pour toute la conversation", true],["Le résumé de la conversation", false],["La réponse automatique de bienvenue", false]] },
    { q: "Comment rendre un assistant IA cohérent sur la durée ?", exp: "En incluant le contexte important dans chaque session : qui tu es, ce que tu fais, tes préférences. Les LLMs n'ont pas de mémoire entre sessions — il faut recréer le contexte ou utiliser des outils avec mémoire persistante.", opts: [["L'IA se souvient automatiquement de tout", false],["En incluant le contexte clé dans chaque session ou en utilisant un outil avec mémoire", true],["En gardant la même fenêtre de navigateur ouverte", false],["En payant un abonnement premium", false]] },
    { q: "Vrai ou Faux : Un assistant IA peut gérer ton agenda et envoyer des emails automatiquement.", exp: "Vrai ! Avec les bons outils (comme des agents IA ou des intégrations Zapier), un assistant peut accéder à ton calendrier, envoyer des emails, créer des tâches. C'est ce qu'on appelle l'IA agentique.", opts: [["Vrai", true],["Faux", false]] },
    { q: "Quel est le meilleur cas d'usage pour un assistant IA personnel au travail ?", exp: "La rédaction et reformulation de communications est un des usages les plus universels et rentables. Presque tout le monde écrit des emails, rapports et messages — l'IA peut diviser par 3 le temps passé.", opts: [["Remplacer toutes les réunions", false],["Rédiger, améliorer et adapter ses communications professionnelles", true],["Gérer sa comptabilité personnelle", false],["Surveiller les réseaux sociaux 24h/24", false]] },
  ],
  'c8-l2': [
    { q: "Qu'est-ce que la veille automatique avec l'IA ?", exp: "La veille automatique utilise des outils IA pour surveiller en continu des sources (news, réseaux, concurrents), filtrer les informations pertinentes et les résumer. Tu reçois l'essentiel sans passer des heures à chercher.", opts: [["Surveiller manuellement les actualités chaque matin", false],["Utiliser des outils IA pour surveiller, filtrer et résumer automatiquement les informations pertinentes", true],["Créer des alertes Google basiques", false],["Lire des newsletters quotidiennes", false]] },
    { q: "Quel outil combine le mieux recherche en temps réel et synthèse IA ?", exp: "Perplexity AI est spécialement conçu pour ça : il cherche sur le web en temps réel et synthétise les résultats avec citations. Idéal pour la veille car il combine fraîcheur de l'info et analyse IA.", opts: [["ChatGPT sans plugins", false],["Perplexity AI", true],["Google Traduction", false],["Notion AI", false]] },
    { q: "Comment automatiser une veille concurrentielle avec Zapier et l'IA ?", exp: "Workflow typique : Zapier surveille les mentions de tes concurrents (Google Alerts ou RSS) → envoie à un LLM pour analyse et résumé → poste le résumé dans Slack ou par email. Entièrement automatique.", opts: [["C'est impossible sans coder", false],["Zapier détecte les nouvelles infos, les envoie à un LLM pour résumé, puis notifie par email ou Slack", true],["Il faut un stagiaire pour surveiller manuellement", false],["Seules les grandes entreprises peuvent le faire", false]] },
    { q: "Vrai ou Faux : Une veille IA peut remplacer complètement l'analyse humaine.", exp: "Faux ! La veille IA excelle pour collecter et filtrer l'information. L'analyse stratégique, la compréhension du contexte business et les décisions restent humaines. L'IA prépare, l'humain décide.", opts: [["Vrai", false],["Faux", true]] },
    { q: "Quelle est la fréquence idéale pour une veille automatisée ?", exp: "Ça dépend du secteur et de l'enjeu. Pour la tech et les réseaux sociaux : quotidien ou temps réel. Pour la veille concurrentielle : hebdomadaire suffit souvent. L'important est la régularité et la pertinence.", opts: [["Une fois par mois minimum", false],["Ça dépend du secteur — quotidien pour les sujets rapides, hebdomadaire pour les autres", true],["Toutes les heures sans exception", false],["Uniquement quand on a le temps", false]] },
  ],
  'c8-l3': [
    { q: "Qu'est-ce que la 'rédaction augmentée' par l'IA ?", exp: "La rédaction augmentée c'est un mode de travail où l'humain et l'IA collaborent : l'humain apporte les idées, le contexte et le jugement, l'IA structure, rédige et améliore. Le résultat est meilleur et plus rapide.", opts: [["Laisser l'IA écrire tout le contenu sans relecture", false],["Collaborer avec l'IA où l'humain apporte les idées et l'IA structure et rédige", true],["Utiliser l'IA uniquement pour corriger l'orthographe", false],["Copier-coller les réponses de l'IA directement", false]] },
    { q: "Comment produire du contenu 5x plus vite avec l'IA ?", exp: "Workflow efficace : brief rapide (5 min) → IA génère un premier jet → humain révise et personnalise (10 min) → IA affine selon les retours (2 min). Ce qui prenait 1h se fait en 15-20 minutes.", opts: [["Demander à l'IA de tout faire sans intervenir", false],["Brief rapide → IA génère → humain révise → IA affine — cycle itératif rapide", true],["Écrire soi-même puis demander à l'IA de réécrire", false],["Utiliser des templates fixes sans personnalisation", false]] },
    { q: "Vrai ou Faux : Le contenu généré par IA est toujours détectable.", exp: "Faux ! Les détecteurs de contenu IA ont un taux d'erreur élevé et signalent parfois du contenu humain comme IA. Un contenu bien révisé et personnalisé est très difficile à distinguer d'un texte purement humain.", opts: [["Vrai", false],["Faux", true]] },
    { q: "Quelle est la règle d'or de la rédaction augmentée ?", exp: "Toujours relire, vérifier les faits et personnaliser. L'IA peut halluciner des faits, manquer de nuance ou produire un style générique. Ta valeur ajoutée c'est la vérification, le contexte et l'authenticité.", opts: [["Publier directement sans relire pour gagner du temps", false],["Toujours relire, vérifier les faits et personnaliser le contenu", true],["N'utiliser l'IA que pour les textes courts", false],["Toujours mentionner que le texte est écrit par IA", false]] },
    { q: "Pour quel type de contenu l'IA est-elle la plus efficace en rédaction ?", exp: "Les contenus structurés et répétitifs : fiches produits, descriptions, emails types, rapports standardisés, posts réseaux sociaux. L'IA excelle quand il y a un format clair à respecter et des variations à produire.", opts: [["Les discours politiques originaux", false],["Les contenus structurés et répétitifs : fiches produits, emails types, posts réseaux", true],["Les œuvres littéraires profondes", false],["Les analyses philosophiques complexes", false]] },
  ],
  'c8-l4': [
    { q: "Comment analyser un fichier CSV avec ChatGPT ?", exp: "Dans ChatGPT (version avec Advanced Data Analysis), tu uploades le CSV et poses tes questions en langage naturel. L'IA écrit et exécute le code Python nécessaire pour analyser tes données.", opts: [["C'est impossible, ChatGPT ne lit pas les fichiers", false],["Uploader le CSV et poser des questions en langage naturel — l'IA génère et exécute le code", true],["Copier-coller tout le contenu du CSV dans le chat", false],["Convertir d'abord en PDF", false]] },
    { q: "Vrai ou Faux : L'IA peut créer des graphiques à partir de données brutes.", exp: "Vrai ! ChatGPT Advanced Data Analysis et Claude peuvent générer des visualisations (graphiques, histogrammes, scatter plots) directement à partir de tes données. Tu décris ce que tu veux voir, l'IA le crée.", opts: [["Vrai", true],["Faux", false]] },
    { q: "Quelle précaution prendre avant d'envoyer des données à une IA pour analyse ?", exp: "Anonymiser les données personnelles avant de les partager. Ne jamais envoyer de données clients identifiables, données médicales ou financières confidentielles sans vérifier la politique de confidentialité de l'outil.", opts: [["Aucune, les IA sont sécurisées par défaut", false],["Anonymiser les données personnelles et vérifier la politique de confidentialité", true],["Compresser les données en ZIP", false],["Demander la permission à l'IA", false]] },
    { q: "Pour analyser des données avec l'IA, quel prompt est le plus efficace ?", exp: "Un prompt qui précise le contexte des données, l'objectif de l'analyse et le format de sortie souhaité. L'IA a besoin de comprendre ce que tu cherches pour produire une analyse pertinente.", opts: [["'Analyse mes données'", false],["'Voici des ventes par région sur 12 mois. Identifie les 3 tendances principales et les anomalies, sous forme de bullet points pour un comité de direction'", true],["'Que vois-tu dans ce fichier ?'", false],["'Fais des graphiques'", false]] },
    { q: "Qu'est-ce que l'analyse de sentiment avec l'IA ?", exp: "L'analyse de sentiment détermine automatiquement si un texte est positif, négatif ou neutre. Très utile pour analyser des avis clients, des commentaires réseaux sociaux ou des retours d'enquêtes en masse.", opts: [["Analyser les émotions des développeurs IA", false],["Déterminer automatiquement si des textes sont positifs, négatifs ou neutres", true],["Détecter les fautes de sentiment dans un texte", false],["Mesurer l'enthousiasme des équipes", false]] },
  ],
  'c8-l5': [
    { q: "Qu'est-ce qui différencie un utilisateur avancé de l'IA d'un débutant ?", exp: "L'utilisateur avancé sait formuler des prompts précis, itérer rapidement, combiner plusieurs outils, vérifier les résultats et intégrer l'IA dans ses workflows. Il traite l'IA comme un partenaire, pas un oracle.", opts: [["Il utilise l'IA plus souvent", false],["Il sait formuler des prompts précis, combiner les outils et intégrer l'IA dans ses workflows", true],["Il a un abonnement premium partout", false],["Il connaît la programmation Python", false]] },
    { q: "Vrai ou Faux : Maîtriser l'IA aujourd'hui est un avantage compétitif majeur.", exp: "Vrai ! Selon McKinsey, les entreprises qui adoptent l'IA augmentent leur productivité de 20-40%. Les individus qui maîtrisent l'IA accomplissent en 1h ce qui prenait une journée. C'est une compétence différenciante.", opts: [["Vrai", true],["Faux", false]] },
    { q: "Quelle est la meilleure façon de progresser en IA ?", exp: "La pratique régulière sur des cas réels est irremplaçable. Lire sur l'IA c'est bien, l'utiliser quotidiennement sur des vrais problèmes c'est transformateur. Commence par un outil, maîtrise-le, puis étends.", opts: [["Obtenir un diplôme en informatique", false],["Pratiquer régulièrement sur des cas réels de ta vie professionnelle", true],["Regarder des vidéos YouTube uniquement", false],["Attendre que l'IA soit plus mature", false]] },
    { q: "Comment évaluer si un outil IA vaut vraiment le coût de son abonnement ?", exp: "Calcule le temps gagné × ta valeur horaire. Si un outil à 20€/mois te fait gagner 2h par semaine et que ton temps vaut 50€/h, le ROI est de 400€/mois pour 20€ investis. Le calcul est souvent évident.", opts: [["Compter le nombre de fonctionnalités proposées", false],["Calculer le temps gagné multiplié par ta valeur horaire et comparer au coût", true],["Attendre les avis d'autres utilisateurs", false],["Tester pendant 1 an avant de décider", false]] },
    { q: "Quel est le message clé de ce parcours NeuroPilot ?", exp: "L'IA n'est pas une menace pour ceux qui la maîtrisent — c'est un multiplicateur de compétences. Les humains qui travaillent avec l'IA surpasseront ceux qui ne le font pas. Tu as maintenant les bases pour piloter ton futur.", opts: [["L'IA va tout automatiser et remplacer les humains", false],["L'IA est un multiplicateur de compétences pour ceux qui la maîtrisent", true],["Il faut apprendre à programmer pour utiliser l'IA", false],["L'IA n'est utile que pour les grandes entreprises", false]] },
  ],
}

for(const [slug, exercises] of Object.entries(data)) {
  const lessonId = bySlug[slug]
  if(!lessonId) { console.log('Introuvable:', slug); continue }
  const shuffled = exercises.map(ex => ({ ...ex, opts: [...ex.opts].sort(() => Math.random() - 0.5) }))
  for(let i=0; i<shuffled.length; i++) {
    const ex = shuffled[i]
    const created = await p.exercise.create({
      data: { lessonId, type: ex.opts.length === 2 ? 'vrai_faux' : 'qcm', question: ex.q, explanation: ex.exp, order: i+1, xpValue: 5 }
    })
    for(let j=0; j<ex.opts.length; j++) {
      await p.answerOption.create({
        data: { exerciseId: created.id, text: ex.opts[j][0], isCorrect: ex.opts[j][1], order: j }
      })
    }
  }
}
console.log('Chapitre 8 ajouté !')
await p.$disconnect()
