import { PrismaClient } from '@prisma/client'
const p = new PrismaClient()

const lessons = await p.lesson.findMany({where:{slug:{in:['c7-l1','c7-l2','c7-l3','c7-l4','c7-l5']}}})
for(const l of lessons) {
  const exos = await p.exercise.findMany({where:{lessonId:l.id}})
  for(const e of exos) await p.answerOption.deleteMany({where:{exerciseId:e.id}})
  await p.exercise.deleteMany({where:{lessonId:l.id}})
}
const bySlug = Object.fromEntries(lessons.map(l => [l.slug, l.id]))

const data = {
  'c7-l1': [
    { q: "Qu'est-ce qu'un biais dans un modèle d'IA ?", exp: "Un biais survient quand le modèle produit des résultats systématiquement favorables ou défavorables pour certains groupes. Il vient souvent des données d'entraînement qui reflètent des inégalités existantes.", opts: [["Une erreur aléatoire dans les prédictions", false],["Un résultat systématiquement favorable ou défavorable pour certains groupes", true],["Un bug de programmation", false],["Une lenteur du modèle", false]] },
    { q: "D'où viennent principalement les biais dans les IA ?", exp: "Les biais viennent avant tout des données d'entraînement. Si les données reflètent des inégalités historiques (moins de femmes dans certains métiers, surreprésentation de certaines ethnies), le modèle les reproduit.", opts: [["Des développeurs malveillants", false],["Des données d'entraînement qui reflètent des inégalités existantes", true],["Des serveurs défectueux", false],["Du manque de puissance de calcul", false]] },
    { q: "Quel est un exemple célèbre de biais dans un système d'IA ?", exp: "Amazon a dû abandonner un outil de recrutement IA en 2018 car il pénalisait les CV de femmes — entraîné sur 10 ans de recrutements historiquement dominés par des hommes, il avait appris cette discrimination.", opts: [["Google Maps qui évite certains quartiers", false],["L'outil de recrutement d'Amazon qui pénalisait les femmes", true],["Netflix qui recommande trop de films d'action", false],["Siri qui ne comprend pas les accents", false]] },
    { q: "Vrai ou Faux : Une IA entraînée sur plus de données est forcément moins biaisée.", exp: "Faux ! Plus de données biaisées = plus de biais. Si les données reflètent des discriminations, augmenter leur volume amplifie le problème. La qualité et la diversité des données comptent plus que la quantité.", opts: [["Vrai", false],["Faux", true]] },
    { q: "Comment réduire les biais dans un système d'IA ?", exp: "Plusieurs approches : diversifier les données d'entraînement, inclure des équipes diverses, auditer régulièrement les résultats, tester sur différents groupes. Il n'existe pas de solution magique — c'est un travail continu.", opts: [["Utiliser uniquement des données récentes", false],["Diversifier les données, auditer les résultats et inclure des équipes diverses", true],["Augmenter la puissance de calcul", false],["Supprimer toutes les données sensibles", false]] },
  ],
  'c7-l2': [
    { q: "Qu'est-ce qu'une 'hallucination' d'un LLM ?", exp: "Une hallucination c'est quand l'IA génère des informations fausses avec l'air d'être sûre d'elle. Elle peut inventer des citations, des faits, des références qui n'existent pas. C'est un problème majeur.", opts: [["Quand l'IA génère des images", false],["Quand l'IA invente des informations fausses avec confiance", true],["Quand l'IA refuse de répondre", false],["Quand l'IA est trop lente", false]] },
    { q: "Pourquoi les LLMs hallucinent-ils ?", exp: "Les LLMs génèrent le texte le plus statistiquement probable, pas forcément le plus vrai. Ils n'ont pas de mécanisme pour vérifier les faits — ils 'extrapolent' avec confiance même quand ils ne savent pas.", opts: [["Parce qu'ils manquent de mémoire RAM", false],["Parce qu'ils génèrent le texte probable sans mécanisme de vérification des faits", true],["Parce qu'internet contient de fausses informations", false],["Parce qu'ils sont mal programmés", false]] },
    { q: "Comment se protéger des hallucinations d'une IA ?", exp: "Toujours vérifier les informations importantes avec des sources fiables. Demander à l'IA de citer ses sources. Être particulièrement vigilant sur les chiffres, dates, noms et citations.", opts: [["Faire confiance à l'IA car elle est entraînée sur internet", false],["Vérifier les informations importantes avec des sources fiables", true],["Utiliser uniquement les IA payantes", false],["Poser la question plusieurs fois", false]] },
    { q: "Vrai ou Faux : Une IA qui dit 'je ne sais pas' est moins fiable qu'une qui répond toujours.", exp: "Faux ! Une IA qui reconnaît ses limites est plus fiable. Les IA qui répondent toujours avec confiance sont plus dangereuses car elles peuvent induire en erreur sur des sujets qu'elles ne maîtrisent pas.", opts: [["Vrai", false],["Faux", true]] },
    { q: "Le RAG (Retrieval Augmented Generation) aide à réduire les hallucinations car :", exp: "Le RAG ancre les réponses dans des documents réels et vérifiés. Au lieu d'extrapoler, l'IA s'appuie sur des sources concrètes. Elle peut aussi citer ces sources, ce qui permet la vérification.", opts: [["Il rend l'IA plus rapide", false],["Il ancre les réponses dans des documents réels et vérifiables", true],["Il supprime les données incorrectes", false],["Il connecte l'IA à Wikipedia", false]] },
  ],
  'c7-l3': [
    { q: "Quand tu utilises ChatGPT gratuitement, que se passe-t-il avec tes conversations ?", exp: "Par défaut, OpenAI peut utiliser tes conversations pour améliorer ses modèles. Il est possible de désactiver cette option dans les paramètres. Pour des données sensibles, utilise la version entreprise ou désactive l'historique.", opts: [["Elles sont supprimées immédiatement", false],["Elles peuvent être utilisées pour entraîner les modèles d'OpenAI", true],["Elles sont partagées avec des tiers", false],["Elles sont chiffrées et inaccessibles", false]] },
    { q: "Vrai ou Faux : Il est prudent de partager des données confidentielles d'entreprise avec ChatGPT.", exp: "Faux ! Des données confidentielles partagées avec un LLM peuvent être utilisées pour l'entraînement ou exposées en cas de faille. Samsung a vécu un incident majeur quand des employés ont partagé du code source propriétaire.", opts: [["Vrai", false],["Faux", true]] },
    { q: "Qu'est-ce que le RGPD implique pour les outils IA en Europe ?", exp: "Le RGPD exige que les données personnelles soient traitées avec consentement, de façon transparente et sécurisée. Les entreprises IA doivent expliquer comment elles utilisent les données et permettre leur suppression.", opts: [["Les IA sont interdites en Europe", false],["Les données personnelles doivent être traitées avec consentement et transparence", true],["Seules les IA européennes sont autorisées", false],["Les IA ne peuvent pas traiter de texte en français", false]] },
    { q: "Comment protéger sa vie privée quand on utilise des outils IA ?", exp: "Éviter de partager des informations personnelles identifiables, utiliser des pseudonymes, désactiver l'historique quand possible, lire les politiques de confidentialité, utiliser des versions entreprise pour les données sensibles.", opts: [["Utiliser l'IA uniquement sur téléphone", false],["Éviter les données personnelles, désactiver l'historique, utiliser les versions entreprise", true],["Changer de mot de passe régulièrement", false],["Utiliser un VPN suffit", false]] },
    { q: "Qu'est-ce que le 'droit à l'oubli' en lien avec l'IA ?", exp: "Le droit à l'oubli (RGPD) permet de demander la suppression de ses données personnelles. Pour les LLMs, c'est complexe car les données sont 'intégrées' dans les poids du modèle, pas stockées comme un fichier.", opts: [["Le droit de ne pas utiliser l'IA", false],["Le droit de demander la suppression de ses données personnelles", true],["Le droit d'oublier ses mots de passe", false],["Le droit de corriger les erreurs de l'IA", false]] },
  ],
  'c7-l4': [
    { q: "Quels métiers sont les PLUS menacés par l'IA selon les études récentes ?", exp: "Les métiers les plus menacés sont ceux basés sur des tâches répétitives et codifiables : saisie de données, certaines tâches comptables, service client basique, traduction standard. Les tâches créatives et relationnelles sont moins exposées.", opts: [["Chirurgiens et pompiers", false],["Saisie de données, tâches administratives répétitives, service client basique", true],["Artistes et psychologues", false],["Agriculteurs et plombiers", false]] },
    { q: "Vrai ou Faux : L'IA va principalement détruire des emplois sans en créer.", exp: "Faux ! Historiquement, chaque révolution technologique a détruit certains emplois et en a créé de nouveaux. L'IA crée des métiers : prompt engineer, AI trainer, responsable éthique IA, spécialiste MLOps...", opts: [["Vrai", false],["Faux", true]] },
    { q: "Qu'est-ce que l'augmentation humaine par l'IA ?", exp: "L'augmentation consiste à utiliser l'IA comme outil pour rendre les humains plus productifs et efficaces, pas pour les remplacer. Un médecin avec l'IA diagnostique mieux qu'un médecin seul ou une IA seule.", opts: [["Remplacer les humains par des robots", false],["Utiliser l'IA pour rendre les humains plus productifs et efficaces", true],["Implanter des puces dans le cerveau humain", false],["Former les humains à programmer l'IA", false]] },
    { q: "Quelle compétence sera la plus précieuse à l'ère de l'IA ?", exp: "Savoir collaborer efficacement avec l'IA — poser les bonnes questions, vérifier les résultats, apporter le jugement humain — sera plus précieux que de savoir tout faire soi-même. L'IA amplifie les compétences existantes.", opts: [["Savoir programmer en Python", false],["Savoir collaborer avec l'IA et apporter le jugement humain", true],["Mémoriser des informations", false],["Travailler plus vite que l'IA", false]] },
    { q: "Comment se préparer au marché du travail à l'ère de l'IA ?", exp: "Développer des compétences hybrides : maîtriser les outils IA de son secteur, renforcer les compétences humaines irremplaçables (créativité, empathie, leadership), rester en veille et apprendre continuellement.", opts: [["Éviter complètement les outils IA", false],["Développer des compétences hybrides alliant IA et compétences humaines uniques", true],["Se spécialiser uniquement en programmation", false],["Attendre que la situation se stabilise", false]] },
  ],
  'c7-l5': [
    { q: "Qu'est-ce que l'IA 'responsable' ?", exp: "L'IA responsable est développée et utilisée en respectant des principes éthiques : transparence, équité, respect de la vie privée, sécurité, responsabilité. C'est un cadre pour que l'IA bénéficie à tous.", opts: [["Une IA qui ne fait jamais d'erreurs", false],["Une IA développée en respectant des principes éthiques et au bénéfice de tous", true],["Une IA programmée par des responsables d'entreprise", false],["Une IA utilisée uniquement par des experts", false]] },
    { q: "Qu'est-ce que l'AI Act européen ?", exp: "L'AI Act est la première loi mondiale sur l'IA, adoptée par l'UE en 2024. Elle classe les IA par niveau de risque et impose des obligations selon ce niveau. Les IA à haut risque (recrutement, justice) sont très encadrées.", opts: [["Une recommandation non contraignante sur l'IA", false],["La première loi mondiale contraignante sur l'IA, classant les systèmes par niveau de risque", true],["Un accord commercial sur les technologies IA", false],["Un label qualité pour les produits IA", false]] },
    { q: "Vrai ou Faux : Les deepfakes sont illégaux dans tous les pays.", exp: "Faux ! La législation varie selon les pays et évolue rapidement. Certains deepfakes sont illégaux (pornographie non consentie, fraude), d'autres sont dans une zone grise. La loi peine à suivre la technologie.", opts: [["Vrai", false],["Faux", true]] },
    { q: "Qu'est-ce que la transparence algorithmique ?", exp: "La transparence algorithmique signifie qu'on peut comprendre et expliquer pourquoi une IA a pris une décision. Crucial quand l'IA prend des décisions qui affectent des humains : crédit, recrutement, justice.", opts: [["Rendre le code source public", false],["Pouvoir expliquer pourquoi l'IA a pris une décision donnée", true],["Informer les utilisateurs qu'ils parlent à une IA", false],["Publier les données d'entraînement", false]] },
    { q: "Quel principe éthique fondamental doit guider le développement de l'IA ?", exp: "Le principe de bienfaisance — l'IA doit bénéficier à l'humanité. Tous les autres principes (transparence, équité, sécurité) servent cet objectif. La technologie doit être au service des humains, pas l'inverse.", opts: [["Maximiser les profits des entreprises IA", false],["L'IA doit bénéficier à l'humanité et respecter la dignité humaine", true],["L'IA doit être la plus puissante possible", false],["L'IA doit remplacer les décisions humaines faillibles", false]] },
  ],
}

for(const [slug, exercises] of Object.entries(data)) {
  const lessonId = bySlug[slug]
  if(!lessonId) { console.log('Introuvable:', slug); continue }
  const shuffled = exercises.map(ex => ({ ...ex, opts: [...ex.opts].sort(() => Math.random() - 0.5) }))
  for(let i=0; i<shuffled.length; i++) {
    const ex = shuffled[i]
    const created = await p.exercise.create({
      data: { lessonId, type: ex.opts.length === 2 ? 'vrai_faux' : 'qcm', question: ex.q, explanation: ex.exp, order: i+1, xpValue: 5 }
    })
    for(let j=0; j<ex.opts.length; j++) {
      await p.answerOption.create({
        data: { exerciseId: created.id, text: ex.opts[j][0], isCorrect: ex.opts[j][1], order: j }
      })
    }
  }
}
console.log('Chapitre 7 ajouté !')
await p.$disconnect()
